src/routes/public.py
"""
    file that contains all the public routes
"""

from flask import render_template, request, redirect, url_for, Blueprint, abort
from database import db
from models import Artwork, Client
import uuid
import random
from flask import session

# blueprint for the public routes
public_routes = Blueprint('public', __name__, url_prefix='/')


@public_routes.route('/')
def index():
    """ route for the home page """
    # random artworks for home page
    if 'cart' not in session:
        session['cart'] = []

    random_artworks = [random.choice(Artwork.query.filter_by(category_id=1).all()), random.choice(Artwork.query.filter_by(category_id=2).all()), random.choice(Artwork.query.filter_by(category_id=3).all())]
    print(random_artworks)
    current_page = 'home'
    return render_template('index.html', current_page=current_page, cache_id=uuid.uuid4(), random_artworks=random_artworks, artworks_in_cart=session['cart'])


@public_routes.route('<category>/')
def each(category):
    """ route for each category """
    if 'cart' not in session:
        session['cart'] = []

    if category == 'painting':
        current_page = 'painting'
        paintings = Artwork.query.filter_by(category_id=1).all()
        rNum = random.choice([4])
        return render_template('painting.html', current_page=current_page, cache_id=uuid.uuid4(), paintings=paintings, rNum=str(rNum), artworks_in_cart=session['cart'])
    elif category == 'print':
        current_page = 'print'
        rNum = random.choice([6])
        prints = Artwork.query.filter_by(category_id=2).all()
        return render_template('prints.html', current_page=current_page, cache_id=uuid.uuid4(), prints=prints, rNum=str(rNum), artworks_in_cart=session['cart'])
    elif category == 'sculpture':
        current_page = 'sculpture'
        rNum = random.choice([6])
        sculptures = Artwork.query.filter_by(category_id=3).all()
        return render_template('sculpture.html', current_page=current_page, cache_id=uuid.uuid4(), sculptures=sculptures, rNum=str(rNum), artworks_in_cart=session['cart'])
    else:
        abort(404)

@public_routes.route('<category>/<int:id>/details')
def details(category, id):
    """ route for each artwork details """
    if category not in ['painting', 'print', 'sculpture']:
        abort(404)

    current_page = category
    artwork = Artwork.query.filter_by(id=id).first()
    similar_artworks = Artwork.query.filter_by(category_id=artwork.categories.id).limit(4).all()

    if 'cart' not in session:
        session['cart'] = []

    if artwork in similar_artworks:
        similar_artworks.remove(artwork)
    print(similar_artworks)
    return render_template('artwork_details.html', current_page=current_page, cache_id=uuid.uuid4(), artwork=artwork, similar_artworks=similar_artworks, artworks_in_cart=session['cart'])

# ---- cart routes ----
@public_routes.route('/cart')
def cart():
    """ route for the cart page """
    total = 0
    # ids = [Artwork.query.filter_by(id=id).first().id]
    if 'cart' in session:
        artworks_in_cart = [Artwork.query.filter_by(id=id).first() for id in session['cart']]
        for artwork in artworks_in_cart:
            total += artwork.price
    else:
        artworks_in_cart = []
    print(artworks_in_cart, total)
    return render_template('cart.html', cache_id=uuid.uuid4(), artworks_in_cart=artworks_in_cart, total_of_prices=total)

@public_routes.route('/add/<int:id>/to_cart')
def add_to_cart(id):
    """ route for adding an artwork to the cart """
    if 'cart' not in session:
        session['cart'] = []
    if id not in session['cart']:
        session['cart'].append(id)

    artworks_in_cart = [ Artwork.query.filter_by(id=id).first() for id in session['cart'] ]
    print(session['cart'])
    print(artworks_in_cart)

    return redirect(url_for('public.cart', cache_id=uuid.uuid4()))

@public_routes.route('/remove/<int:id>/from_cart')
def remove_from_cart(id):
    """ route for removing an artwork from the cart """
    if 'cart' not in session:
        session['cart'] = []
    if id in session['cart']:
        session['cart'].remove(id)

    artworks_in_cart = [ Artwork.query.filter_by(id=id).first() for id in session['cart'] ]
    print(session['cart'])
    print(artworks_in_cart)

    return redirect(url_for('public.cart', cache_id=uuid.uuid4()))

# ---- end cart routes ----

# ---- checkout ----
@public_routes.route('/cart/checkout')
def checkout():
    """ route for the checkout page """
    total = 0
    # ids = [Artwork.query.filter_by(id=id).first().id]
    if 'cart' in session:
        artworks_in_cart = [Artwork.query.filter_by(id=id).first() for id in session['cart']]
        for artwork in artworks_in_cart:
            total += artwork.price
    else:
        artworks_in_cart = []
    print(total, artworks_in_cart)
    return render_template('checkout.html', cache_id=uuid.uuid4(), artworks_in_cart=artworks_in_cart, total=total)


@public_routes.route('/cart/checkout/confirm', methods=['GET', 'POST'])
def confirm_checkout():
    """ route for the confirmation page """
    if request.method == 'POST':
        firstname = request.form.get('firstname')
        lastname = request.form.get('lastname')
        email = request.form.get('email')
        tel = request.form.get('phone')
        address = request.form.get('address')
        total = 0        
        if 'cart' in session:
            ids = session['cart']
            artworks_in_cart = [Artwork.query.filter_by(id=id).first() for id in ids]
            for artwork in artworks_in_cart:
                total += artwork.price
        
        if firstname == '' or lastname == '' or email == '' or tel == '' or address == '':
            return render_template('checkout.html', cache_id=uuid.uuid4(), error='Please fill all the fields',artworks_in_cart=artworks_in_cart, total=total)

        if Client.query.filter_by(email=email).first():
            return render_template('checkout.html', cache_id=uuid.uuid4(), error='This email is already used',artworks_in_cart=artworks_in_cart, total=total)
        
        client = Client(firstname=firstname.capitalize(), lastname=lastname.capitalize(), email=email, tel=tel, address=address)
        print(client)
        db.session.add(client)
        db.session.commit()
        for artwork in artworks_in_cart:
            client.cart_of_artworks.append(artwork)
        db.session.commit()

        artworks = [Artwork.query.filter_by(id=id).first() for id in ids]
        session['cart'] = []


        return render_template('confirmation.html', cache_id=uuid.uuid4(), total=total,client=client, artworks_in_cart=session['cart'], artworks=artworks)
    return render_template('confirmation.html')

src/templates/artwork_details.html
{% extends "public_base.html" %}

{% block content %}
    <section class="section section-lg bg-default mt-3">
      <div class="container">
        <div class="row justify-content-center text-center">
          <div class="col-md-9 col-lg-7 wow-outer">
            <div class="wow slideInDown">
              <!-- <h2>Featured Offers</h2> -->
              <div class="wow slideInDown admin-title">Artwork Details</div>
              <!-- <p class="text-opacity-80">We offer a great variety of  the best Italian dishes to our visitors and guests. Below are some of our most popular main dishes and desserts.</p> -->
            </div>
          </div>
        </div>
        <!-- Add all images -->
        <div class="row">
          <div class="container">
            <div class="row">
              <div class="col-md-6 wow-outer">
                <div class="product-featured-figure d-flex justify-content-center wow slideInLeft">
                    <img src="{{ url_for('static', filename=artwork.image_url[6:]) }}" alt="" width="370" height="395"/>
                </div>
              </div>

              <div class="col-md-6 card p-5 my-4 wow-outer">
                <div class="product-featured-caption wow slideInRight">
                    <div class="product-featured-title"> Name : {{ artwork.name }}</div>
                    <div class="product-featured-title">Author : {{ artwork.artists.lastname + ' ' + artwork.artists.firstname }}</div>
                    <div class="product-featured-description">
                        {{ artwork.categories.label | title }} Technic : {{ artwork.description.split('\n')[0]  }}<br>
                        Creation Date : {{ artwork.description.split('\n')[2]  }}<br>
                        Format : {{ artwork.description.split('\n')[1]  }}
                        {% if artwork.categories.label == 'print' %}
                            <br>
                            Number of impress : {{ artwork.description.split('\n')[3]  }}
                        {% endif %}
                    </div>
                    <p class="big"> Price : ${{ artwork.price }} </p> 
                </div>

                <a class="button button-lg button-cart wow fadeInRight" href="{{ url_for('public.add_to_cart', id=artwork.id) }}">  <span class="fa fa-shopping-cart mr-2"></span> ADD TO CART <span class="fa fa-shopping-cart ml-2"></span></a>
              </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
    <hr>
    <section class="section section-md bg-default">
      <div class="container">
        <div class="row justify-content-center text-center">
          <div class="col-md-9 col-lg-7 wow-outer">
            <div class="wow slideInLeft">
              <!-- <h2>Featured Offers</h2> -->
              <h2 class="">SIMILAR ARTS</h2>
              <!-- <p class="text-opacity-80">We offer a great variety of  the best Italian dishes to our visitors and guests. Below are some of our most popular main dishes and desserts.</p> -->
              <div class="divider mt-3"></div>
            </div>
          </div>
        </div>
        <!-- Add all images -->
        <div class="row">
          {% for artwork in similar_artworks %} 
              <div class="col-md-6 col-lg-4 wow-outer card p-3">
                <div class="wow fadeInUp slideInRight">
                  <div class="product-featured">
                    <div class="product-featured-figure"><img src="{{ url_for('static', filename=artwork.image_url[6:]) }}" alt="" width="370" height="395"/>
                      <div class="product-featured-button"><a class="button button-primary" href="{{ url_for('public.details', category=artwork.categories.label, id=artwork.id) }}">See more</a></div>
                    </div>
                    <div class="product-featured-caption text-center card-footer">
                      <div><a class="product-featured-title" href="#">{{ artwork.name }}</a></div>
                      <p class="big"> Price : ${{ artwork.price }} </p> 
                    </div>
                  </div>
                </div>
              </div>
          {% endfor %}
        </div>
      </div>
    </section>
  {% endblock %}

src/templates/cart.html
{% extends "public_base.html" %}

{% block content %}
    <section class="section section-xxl-3 bg-default content">
        <div class="container">
            <div class="row">
                <div class = "col-md-9 col-lg-7 wow-outer">
                    <div class="wow slideInDown">
                        <h2 class="wow slideInDown">🛒 My Shopping Cart 🛒</h2>
                        <div class="divider mt-3"></div>
                        <div class="mt-2">
                            You're added these following artworks in your shopping cart
                        </div>
                    </div>
                </div>
            </div>

            {% if artworks_in_cart|length == 0 %}
                <p class="row booking-title wow slideInLeft">your shopping cart 🛒 is empty</p>              
            {% else %}
                <div class="wow slideInLeft row row-20 row-lg-30">
                    <table class="table table-striped">
                        <!-- <thead>
                            <tr>
                                <th scope="col" class="text-center">Image</th>
                                <th scope="col" class="text-center">Name</th>
                                <th scope="col" class="text-center">Price</th>
                                <th scope="col" class="text-center">Quantity</th>
                                <th scope="col" class="text-center">Actions</th>
                            </tr>
                        </thead> -->
                        <tbody>
                            {% for artwork in artworks_in_cart %}
                                <tr>
                                    <td class="align-middle">
                                        <figure style="text-align: center;">
                                            <img src="{{ url_for('static', filename=artwork.image_url[6:]) }}" alt="" width="60" height="60"/>
                                        </figure>
                                    </td>
                                    <td class="align-middle text-center">
                                        <div class="d-flex align-items-center justify-content-center">
                                            {{ artwork.name }}
                                        </div>
                                    </td>
                                    <td class="align-middle text-center"> {{ artwork.price }} $</td>
                                    <!-- <td class="align-middle text-center">1</td> -->
                                    <td class="align-middle text-center">
                                        <a href="{{ url_for('public.remove_from_cart', id=artwork.id) }}">
                                            <i style="font-style: normal;" class="fas fa-trash fa-2x"></i>
                                        </a>
                                    </td>
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
                <div class="container cart-price-container mt-5 wow slideInRight">
                    <div class="row d-flex justify-content-between">
                        <div class="cart-label">Total : {{ total_of_prices }}$</div>
                        <div class="d-flex justify-content-center justify-content-sm-end align-items-center">
                            <a href="{{ url_for('public.checkout') }}" class="btn btn-primary btn-md btn-lg">Proceed to checkout</a>
                        </div>
                    </div>
                </div>  
            {% endif %}
        </div>
    </section>
<!-- {% endblock %} -->

src/templates/checkout.html
{% extends "public_base.html" %}

{% block content %}
    <section class="section section-xxl bg-default">
        <div class="container">
            <div class="row">
                <div class="col-lg-4">
                    <div class="col-lg-12">
                        <!-- <div class="booking-title text-center">Payment</div> -->
                        <div class="container-checkout-2">
                            <div class="d-flex justify-content-center">
                                    <img src="{{ url_for('static', filename='images/wave.png') }}" alt="" width="80" height="80">
                                    <img src="{{ url_for('static', filename='images/orange.png') }}" alt="" width="80" height="80">
                               
                                    <img src="{{ url_for('static', filename='images/moov.png') }}" alt="" width="80" height="80">
                                    <img src="{{ url_for('static', filename='images/yellow.png') }}" alt="" width="80" height="80">
                            </div>
                            <!-- <img src="{{ url_for('static', filename='images/operators.png') }}" alt="">
                            
                            <div class="d-flex justify-content-between">
                               
                            </div> -->
                        </div>
                    </div>
                  
                    <div class="col-lg-12 my-3">
                      <div class="container-checkout">
                        <h4> Cart
                          <span class="price" style="color:green">
                            <span class="fa fa-shopping-cart"></span>
                            <b>{{ artworks_in_cart|length }}</b>
                          </span>
                        </h4>
                        {% for artwork in artworks_in_cart %} 
                            <p><a href="#">{{ artwork.name }}</a> <span class="price">${{ artwork.price }}</span></p>
                        {% endfor %}
                        <hr>
                        <p>Total <span class="price" style="color:black"><b>${{ total }}</b></span></p>
                      </div>
                    </div>
                </div>
                <div class="col-lg-8">
                  <div class="container-checkout">
                    <form action="{{ url_for('public.confirm_checkout') }}" method="POST">
                        <div class="row-checkout">
                            <h4 class="col-lg-12 text-center booking-title">Your informations</h4>
                            {% if error %}
                                <div  class="alert-danger text-center my-2 col-lg-12 w-25">
                                    <p>{{ error }}</p>
                                </div>
                            {% endif %}
                            <div class="col-lg-6 my-2">
                                <label for="fname"><span class="fa fa-user  mr-2"></span>First Name</label>
                                <input type="text" id="fname" name="firstname" placeholder="Your first name" data-constraints="@Required">
            
                                <label for="city"><span class="fa fa-institution mr-2"></span>City</label>
                                <input type="text" id="city" name="address" placeholder="Your city" data-constraints="@Required">

                                <label label for="email"><span class="fa fa-envelope mr-2"></span>Email</label>
                                <input type="text" id="email" name="email" placeholder="Your email" data-constraints="@Required">
                            </div>
                
                            <div class="col-lg-6 my-2">
                                <label for="lname"><span class="fa fa-user  mr-2"></span>Last Name</label>
                                <input type="text" id="lname" name="lastname" placeholder="Your last name" data-constraints="@Required">
                                <label for="phone"><span class="fa fa-phone mr-2"></span>Phone Number</label>
                                <input type="text" id="phone" name="phone" placeholder="Your phone number" data-constraints="@PhoneNumber">
                            </div>
                            
                            <div class="col-lg-12">
                                <input type="submit" value="PLACE ORDER" class="btn-checkout">
                            </div>
                        </div>
                    </form>
                  </div>
                </div>
              </div>
        </div>
    </section>
{% endblock %}

src/templates/confirmation.html
{% extends "public_base.html" %}

{% block content %}
<section class="section section-xxl-2 bg-default">
    <div class="container mt-5">
        <div class="row row-5">
            <div class="col-md-8">
                <h3>Thank you Happy <span style="color:green">{{ client.lastname }}</span></h3>
                <p>An email will be sent containing information about your purchase. if you have any questions about your purchase,
                    you can email us or call us.
                </p>
                <p>Thank you for shopping with us.</p>
                <div class="mt-5">
                    <a href="{{ url_for('public.index') }}" class="btn btn-primary">Back to Home</a>
                </div>
            </div>  
            <div class="col-md-4">
                <div class="card">
                    <div class="card-header">Order Summary</div>
                    <div class="card-body">
                        <ul class="list-group list-group-flush">
                            {% for artwork in artworks %}
                                <li class="list-group-item d-flex justify-content-between align-items-center">
                                    {{ artwork.name }}
                                    <span class="badge badge-primary badge-pill">${{ artwork.price }}</span>
                                </li>
                            {% endfor %}
                            <li class="list-group-item d-flex justify-content-between align-items-center">
                                Subtotal
                                <span class="badge badge-primary badge-pill">${{ total }}</span>
                            </li>
                            <li class="list-group-item d-flex justify-content-between align-items-center">
                                Shipping
                                <span class="badge badge-primary badge-pill">Free</span>
                            </li>
                            <li class="list-group-item d-flex justify-content-between align-items-center">
                                Total
                                <span class="badge badge-primary badge-pill">${{ total }}</span>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock %}

src/templates/index.html
{% extends "public_base.html" %}

{% block content %}
  <!-- Swiper-->
  <section class="section section-lg section-main-bunner section-main-bunner-filter text-center">
    <div class="main-bunner-img" style="background-image: url(&quot;static/images/sculpture/sculpture-3.jpg&quot;); background-size: cover;"></div>
    <div class="main-bunner-inner">
      <div class="container">
        <div class="box-default">
          <h1 class="box-default-title">Welcome</h1>
          <div class="box-default-decor"></div>
          <p class="big box-default-text">Our gallery features unique and inspiring works of art that have been created using sustainable materials and repurposed items. Here, you can explore the beauty of art while also making a positive impact on the environment. </p>
        </div>
      </div>
    </div>
  </section>

  <section class="section-md bg-default">
    <div class="container wow-outer">
      <h2 class="text-center wow slideInRight">New Arts </h2>
      <!-- Owl Carousel-->
      <div class="owl-carousel wow fadeInUp" data-items="1" data-md-items="2" data-lg-items="3" data-dots="true" data-nav="false" data-stage-padding="15" data-loop="false" data-margin="30" data-mouse-drag="false">
        {% for artwork in random_artworks %}
            <div class="wow-outer">
              <div class="wow fadeInUp">
                <div class="product-featured">
                  <div class="product-featured-figure"><img src="{{ url_for('static', filename=artwork.image_url[6:]) }}" alt="" width="370" height="395"/>
                    <div class="product-featured-button">
                        <h4 class="text-white">{{ artwork.categories.label | title }}</h4>
                    </div>
                  </div>
                </div>
                <div class="text-center mt-4">
                  <a class="post-corporate-link" href="{{ url_for('public.each', category = artwork.categories.label) }}">Read more<span class="icon linearicons-arrow-right"></span></a>
                </div>
              </div>
            </div>
        {% endfor %}    
    </div>
  </section>
{% endblock %}

src/templates/public_base.html
<!DOCTYPE html>
<html class="wide wow-animation" lang="en"> 
  <head>
    <title>Artsvert | Home</title>  
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, height=device-height, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <link rel="icon" href="{{ url_for('static', filename='images/favicon.ico') }}" type="image/x-icon">
    <link rel="stylesheet" type="text/css" href="//fonts.googleapis.com/css?family=Poppins:300,300i,400,500,600,700,800,900,900i%7CPT+Serif:400,700">
    <link rel="stylesheet" href="{{ url_for('static', filename='styles/bootstrap.css') }}?{{ cache_id }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='styles/fonts.css') }}?{{ cache_id }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='styles/style.css') }}?{{ cache_id }}">
  </head>
  <body>
    <!-- Loading system -->
    <div class="preloader">
      <div class="preloader-body">
        <div class="cssload-container">
          <div class="cssload-speeding-wheel"></div>
        </div>
        <p>Loading...</p>
      </div>
    </div>
  <!-- main div  -->
    <div class="page">
      <!-- Page Header-->
      <header class="section page-header">
        <!-- RD Navbar-->
        <div class="rd-navbar-wrap">
          <nav class="rd-navbar rd-navbar-classic" data-layout="rd-navbar-fixed" data-sm-layout="rd-navbar-fixed" data-md-layout="rd-navbar-fixed" data-md-device-layout="rd-navbar-fixed" data-lg-layout="rd-navbar-static" data-lg-device-layout="rd-navbar-static" data-xl-layout="rd-navbar-static" data-xl-device-layout="rd-navbar-static" data-lg-stick-up-offset="46px" data-xl-stick-up-offset="46px" data-xxl-stick-up-offset="46px" data-lg-stick-up="true" data-xl-stick-up="true" data-xxl-stick-up="true">
            <div class="rd-navbar-main-outer">
              <div class="rd-navbar-main">
                <!-- RD Navbar Panel-->
                <div class="rd-navbar-panel"> 
                  <!-- RD Navbar Toggle-->
                  <button class="rd-navbar-toggle" data-rd-navbar-toggle=".rd-navbar-nav-wrap"><span></span></button>
                  <!-- RD Navbar Brand-->
                  <!-- logo div -->
                    <!-- <div class="rd-navbar-brand"><a href="{{ url_for('public.index') }}"><img class="brand-logo-light" src="../static/images/logo-default-280x113.png" alt="" width="140" height="57" srcset="images/logo-default-280x113.png 2x"/></a></div> -->
                  <!--End logo div -->
                </div>
                <div class="rd-navbar-main-element">
                  <div class="rd-navbar-nav-wrap">
                    <!-- RD Navbar Nav-->
                    <ul class="rd-navbar-nav">
                      <li class="rd-nav-item {% if current_page == 'home' %}active{% endif %}"> <a class="rd-nav-link" href="{{ url_for('public.index')}}">Home</a> </li>
                      <li class="rd-nav-item {% if current_page == 'painting' %}active{% endif %}"><a class="rd-nav-link" href="{{ url_for('public.each', category = 'painting') }}">Painting</a> </li>
                      <li class="rd-nav-item {% if current_page == 'print' %}active{% endif %}"><a class="rd-nav-link" href="{{ url_for('public.each', category = 'print') }} ">Prints</a> </li>
                      <li class="rd-nav-item {% if current_page == 'sculpture' %}active{% endif %}"><a class="rd-nav-link" href="{{ url_for('public.each', category = 'sculpture') }}">Sculpture</a> </li>
                    </ul> 

                    
                    <a class="button button-white" href="{{ url_for('public.cart') }}"> <span class="fa fa-shopping-cart mr-2"></span> Cart <span class="badge bg-dark text-white ms-1 rounded-pill">{{ artworks_in_cart|length }}</span></a>
                    <a class="button button-white button-sm" href="#"> </span> <span class="fa fa-user mr-2"></span>Login <span class="fa fa-user ml-2"></span></a>
                  </div>
                </div>
                
                <a class="button button-white button-sm" href="{{ url_for('public.cart') }}"> <span class="fa fa-shopping-cart mr-2"></span> Cart <span class="badge bg-dark text-white ms-1 rounded-pill">{{ artworks_in_cart|length }}</span></a>
                <a class="button button-white button-sm" href="#"><span class="fa fa-user mr-2"></span> Login <span class="fa fa-user ml-2"></span></a>

              </div>
            </div>
          </nav>
        </div>
      </header>
      <!-- End header -->
      
      {% block content %}
      {% endblock %}
      
      <!-- Page Footer-->
      <footer class="section footer-minimal context-dark">
        <div class="container wow-outer">
          <div class="wow fadeIn">
            <div class="row row-60">
              <div class="col-12 my-3">
                <a href="index.html">
                  <!-- <img src="../static/images/logo-default1-140x57.png" alt="" width="140" height="57" srcset="../static/images/logo-default-280x113.png 2x"/> -->
                </a>
              </div>
              <div class="col-12 my-3">
                <ul class="footer-minimal-nav">
                  <li><a href="#">Home</a></li>
                  <li><a href="#">Contacts</a></li>
                  <li><a href="#">Sell</a></li>
                  <li><a href="#">About</a></li>
                </ul>
              </div>
              <div class="col-12 my-3">
                <ul class="social-list">
                  <li><a class="icon icon-sm icon-circle icon-circle-md icon-bg-white fa-facebook" href="#"></a></li>
                  <li><a class="icon icon-sm icon-circle icon-circle-md icon-bg-white fa-instagram" href="#"></a></li>
                  <li><a class="icon icon-sm icon-circle icon-circle-md icon-bg-white fa-twitter" href="#"></a></li>
                  <li><a class="icon icon-sm icon-circle icon-circle-md icon-bg-white fa-youtube-play" href="#"></a></li>
                  <li><a class="icon icon-sm icon-circle icon-circle-md icon-bg-white fa-pinterest-p" href="#"></a></li>
                </ul>
              </div>
            </div>
            <p class="rights"><span>&copy;&nbsp; </span><span class="copyright-year"></span><span>&nbsp;</span><span>Artsvert</span><span>.&nbsp;</span><span>All Rights Reserved.</span><span>&nbsp;</span><a href="#">Privacy Policy</a>.</p>
          </div>
        </div>
      </footer>
    </div>
  <!-- End main div
    <div class="snackbars" id="form-output-global"></div>

     <script src="../static/scripts/bootstrap.bundle.min.js?{{ cache_id }}"></script> -->

    <script>
        window.addEventListener('pageshow', function(event) {
            if (event.persisted) {
              window.location.reload();
            }
        });
    </script>
    <script src="{{ url_for('static', filename='scripts/core.min.js')}}?{{ cache_id }}"></script>
    <script src="{{ url_for('static', filename='scripts/script.js')}}?{{ cache_id }}"></script>
  </body>
</html>